DELETE FROM User_Authority;
DELETE FROM Batman_User;
DELETE FROM Authority;
INSERT INTO Authority VALUES ('ROLE_USER');
INSERT INTO Authority VALUES ('ROLE_ANONYMOUS');
INSERT INTO Authority VALUES ('ROLE_ADMIN');
